name: wakelock_plus_platform_interface
description: >-2
  A common platform interface for the wakelock_plus plugin used by the different platform
  implementations.
version: 1.2.1
repository: >-2
  https://github.com/fluttercommunity/wakelock_plus/tree/main/wakelock_plus_platform_interface

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
